[servers]

worker-node-1 ansible_host=15.165.235.24
worker-node-2 ansible_host=43.201.252.229
worker-node-1 ansible_user=ubuntu
worker-node-2 ansible_user=ubuntu


[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/ansible-master-key
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false

#ansible-playbook -i hosts.ini servers -a "apt-get install nginx -y" --become -v
#ansible -i hosts.ini servers -m ping
#ansible -i hosts.ini servers -a "sudo apt-get update"
#ansible -i hosts.ini servers -a "apt-get install nginx -y" --become -v
