- name: Install Packages
  hosts: servers
  become: yes

  vars:
    packages_to_install:
      - tree
      - zip
      - unzip
      - jq
      - wget
      - apache2

  tasks:
    - name: Install package
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install }}"

    - name: Show Message
      loop: "{{ packages_to_install }}"
      debug:
        msg: "Installing {{ item }}"
